/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// This is the base include which defines nsISupports. This class defines
// the QueryInterface method.
#include "nsISupports.idl"


[scriptable, uuid(67fee6fe-2016-4409-9825-4d2ed9ca2bff)]
interface nsIFullscreenService : nsISupports {
  readonly attribute boolean enabled;
};
