# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{acfb3c87-c1cd-4d82-b1ba-0b7c4ecb0318}',
        'contract_ids': ['@mozilla.org/toolkit/pictureinpicture-functions;1'],
        'esModule': 'resource://gre/modules/PictureInPictureFunctions.sys.mjs',
        'constructor': 'PictureInPictureFunctions',
    },
]
